import Head from 'next/head'


import Navbar from '@/components/Navbar'

import Banner from '@/components/Banner'
import Downofbanner from '@/components/Downofbanner'
import Aboutclass from '@/components/Aboutclass'


export default function Home() {
  return (
    <>
      <Head>
        <title>Skill nation</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Navbar/>
        <Banner/>
        <Downofbanner/>
        <Aboutclass/>
        

    
    </>
  )
}
